import * as mongoose from 'mongoose';
import PermissionsSchema from './PermissionsSchema';
import IPermissionsModel from './IPermissionsModel';

export const permissionsSchema = new PermissionsSchema({
    collection: 'Permissions',
});

/**
 * @swagger
 * definitions:
 *   attrb:
 *     type: object
 *     properties:
 *       trainee:
 *         type: array
 *       employee:
 *         type: array
 *       permission:
 *         type: array
 *   permission:
 *     type: object
 *     properties:
 *       _id:
 *         type: integer
 *         description: The unique id generated by Database
 *         format: int64
 *         example: 5fbf9f1827f5c2b1e17b75e2
 *       email:
 *         type: string
 *         description: Email of the user
 *         example: email@successive.tech
 *       resources:
 *         type: object
 *         description: Contains the attributes
 *         $ref: '#/definitions/attrb
 *   UpdatePermissionSuccess:
 *     type: object
 *     properties:
 *       message:
 *         type: string
 *         example: Permissions updated successfully
 *       data:
 *         type: object
 *         $ref: '#/definitions/permission'
 *       status:
 *         type: string
 *         example: success
 *   GetPermissionSuccess:
 *     type: object
 *     properties:
 *       message:
 *         type: string
 *         example: Permissions fetched successfully
 *       data:
 *         type: object
 *         $ref: '#/definitions/permission'
 *       status:
 *         type: string
 *         example: success
 *   ApiError:
 *     type: object
 *     properties:
 *       error:
 *         type: string
 *         example: err
 *       message:
 *         type: string
 *         example: not found
 *       status:
 *         type: integer
 *         example: 404
 *       timeStamp:
 *         type: string
 *         example: 2020-11-24 09-37-32.796Z
 */

export const permissionsModel: mongoose.Model<IPermissionsModel> = mongoose.model<IPermissionsModel>(
    'Permissions',
    permissionsSchema,
    'Permissions',
    true,
);
