import * as mongoose from 'mongoose';
import EmployeeSchema from './EmployeeSchema';
import IEmployeeModel from './IEmployeeModel';

export const employeeSchema = new EmployeeSchema({
    collection: 'Employee',
});

/**
 * @swagger
 * definitions:
 *   employee:
 *     type: object
 *     properties:
 *       _id:
 *         type: integer
 *         description: The unique id generated by Database
 *         format: int64
 *         example: 5fbf9f1827f5c2b1e17b75e2
 *       name:
 *         type: string
 *         description: Name of the user
 *         example: employee 2
 *       role:
 *         type: string
 *         description: The role of the user in the department
 *         example: trainee
 *       parent:
 *         type: string
 *         description: The parent node of the current node.
 *         example: employee 1
 *       ancestors:
 *         type: array
 *         items:
 *           type: string
 *         description: All the ancestors of the current node.
 *         example: employee 1
 *   PostApiSuccess:
 *     type: object
 *     properties:
 *       message:
 *         type: string
 *         example: Employee created successfully
 *       data:
 *         type: object
 *         $ref: '#/definitions/employee'
 *       status:
 *         type: string
 *         example: success
 *   GetApiSuccess:
 *     type: object
 *     properties:
 *       message:
 *         type: string
 *         example: Employee fetched successfully
 *       data:
 *         type: object
 *         properties:
 *           total:
 *             type: number
 *             example: 4
 *           list:
 *             type: object
 *             $ref: '#/definitions/employee'
 *       status:
 *         type: string
 *         example: success
 *   ApiError:
 *     type: object
 *     properties:
 *       error:
 *         type: string
 *         example: err
 *       message:
 *         type: string
 *         example: not found
 *       status:
 *         type: integer
 *         example: 404
 *       timeStamp:
 *         type: string
 *         example: 2020-11-24 09-37-32.796Z
 */

export const employeeModel: mongoose.Model<IEmployeeModel> = mongoose.model<IEmployeeModel>(
    'Employee',
    employeeSchema,
    'Employee',
    true,
);